### ISSUE TITLE
Install/configure Altis

### ISSUE THREAD

**Issue by jazzsequence** [pantheon-systems/hw2022-pantheon-dxp#3]
Add Altis packages to composer file
- ~[x] `altis/core`~ #17  (not required because Accelerate has core included)
- [x] `altis/cms` #20 (had to use [`jazzsequence/altis-cms@12.0-beta4`](https://github.com/jazzsequence/altis-cms/releases/tag/12.0-beta4) to avoid conflicts with WordPress being included as part of the CMS module)
- [x] `altis/cloud` ~(? maybe not?)~ #21 (we don't need most of the cloud module, just including cavalcade)
- [x] `altis/enhanced-search` #22 #28
- ~[ ] `altis/documentation` (could skip this)~
- [x] `altis/media` ~(same, probably wouldn't work without aws services)~ #23
- [x] `altis/privacy` #25 #27
- [x] `altis/seo` #26
- ~[ ] `altis/sso` (can skip this, don't need sso)~
- ~[ ] `altis/multilingual` (not sure what's in this exactly)~ this is just docs
- [x] `altis/workflow` #30 
- [x] `altis/dev-tools` (might not need this) #31 only adding Query Monitor as a dev dependency
- [x] `altis/analytics` #32
- ~[ ] Configure the composer file to turn on/off settings.~ This probably isn't necessary. The requisite parts of Altis/Core aren't autoloading and we probably don't want them to, anyway. Individual components can be activated/deactivated as plugins as usua..
